export type Project = {
  id: string;
  name: string;
  description: string;
  category: "projects" | "design";
  githubUrl?: string;
  liveUrl?: string;
  videoUrl?: string;
  imageUrl?: string;
  tag?: string;
  tech?: string[];
};

export const PROJECTS_DATA: Project[] = [
  {
    id: "project-flux",
    name: "FLux AO",
    category: "projects",
    description: "AI Based MCP tool for Arweave and AO ecosystem",
    githubUrl: "https://github.com/iamkaifyyy/Flux",
    liveUrl: "https://useflux.ar.io",
    videoUrl: "/recordings/flux.mp4",
    tag: "$5000 Grant Recipient",
    tech: ["React", "TypeScript", "Node.js", "Arweave", "Tailwind CSS"],
  },
  {
    id: "project-k0",
    name: "K-V0",
    category: "projects",
    description: "Launching in Mar-2026",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://useflux.ar.io",
    videoUrl: "/recordings/k.mp4",
    tag: "$3000 Grant Recipient",
    tech: ["React", "TypeScript", "AI", "Tailwind CSS"],
  },
  {
    id: "project-c0",
    name: "C-V0",
    category: "projects",
    description: "Launching in Mar-2026",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://useflux.ar.io",
    videoUrl: "/recordings/c.mp4",
    tag: "$4000 Grant Recipient",
    tech: ["React", "TypeScript", "AI Engine"],
  },
  {
    id: "project-lumina",
    name: "Lumina",
    category: "projects",
    description: "Proof-of-Progress Solana",
    githubUrl: "https://github.com/iamkaifyyy/Lumina-Live",
    liveUrl: "https://lumina.example.com",
    videoUrl: "/recordings/lumina.mp4",
    tag: "Building",
    tech: ["Solana", "Solidity", "React", "Wagmi"],
  },
  {
    id: "project-oktopus",
    name: "Oktopus",
    category: "projects",
    description: "Web3 SDK for building web3 apps",
    githubUrl: "https://github.com/iamkaifyyy/oktopus",
    liveUrl: "https://oktopus.example.com",
    videoUrl: "/recordings/oktopus.mp4",
    tag: "Building",
    tech: ["Web3 SDK", "TypeScript", "React"],
  },
  {
    id: "project-rustyworks",
    name: "RustyWorks",
    category: "projects",
    description: "Showcasing complex rust backend architechture with live demos",
    githubUrl: "https://github.com/iamkaifyyy/Rusty-Works",
    liveUrl: "https://rustyworks.example.com",
    videoUrl: "/recordings/rustyworks.mp4",
    tag: "Proof of Work",
    tech: ["Rust", "Actix", "Tokio", "WebSockets"],
  },
  {
    id: "project-arbet",
    name: "ArBet",
    category: "projects",
    description: "Interactive 2D game with ingame web3 contracts with lua",
    githubUrl: "https://github.com/iamkaifyyy/ArBet",
    liveUrl: "https://arbet.example.com",
    videoUrl: "/recordings/arbet.mp4",
    tech: ["Lua", "2D Canvas", "Arweave", "Web3"],
  },
  {
    id: "project-miku",
    name: "Miku-san",
    category: "projects",
    description: "Personal Portfolio creation and built in editor",
    githubUrl: "https://github.com/iamkaifyyy/miku-san-PRIVATE",
    liveUrl: "https://miku-san.example.com",
    videoUrl: "/recordings/miku.mp4",
    tech: ["React.js", "TypeScript", "Tailwind CSS"],
  },
  {
    id: "project-nodestudio",
    name: "NodeStudio",
    category: "projects",
    description: "AI Automation Workflow builder with visual DAG drag-and-drop pipeline editor.",
    githubUrl: "https://github.com/iamkaifyyy/NodeStudio.git",
    liveUrl: "https://node-studio-ecru.vercel.app",
    videoUrl: "/recordings/nodestudio.mp4",
    tag: "AI Automation",
    tech: ["React.js", "TypeScript", "React Flow", "FastAPI"],
  },
  {
    id: "project-rescuenet",
    name: "RescueNet",
    category: "projects",
    description: "Disaster Management platform visualizing live telemetry from USGS, GDACS, and NASA FIRMS.",
    githubUrl: "https://github.com/iamkaifyyy/RescueNet.git",
    liveUrl: "https://rescue-net-pi.vercel.app",
    videoUrl: "/recordings/rescuenet.mp4",
    tag: "🏆 1st Prize Winner",
    tech: ["React.js", "Express.js", "PostgreSQL", "MapLibre GL"],
  },
  {
    id: "project-diagnoslab",
    name: "DiagnosLAB",
    category: "projects",
    description: "Diagnostic lab management platform with RBAC, real-time telemetry, and resource tracking.",
    githubUrl: "https://github.com/iamkaifyyy/DiagnosLAB.git",
    liveUrl: "https://diagnos-lab.vercel.app",
    videoUrl: "/recordings/trustlab.mp4",
    tag: "🏆 1st Prize Winner",
    tech: ["React.js", "Node.js", "Express.js", "MongoDB"],
  },
  {
    id: "project-odyssey",
    name: "Odyssey",
    category: "projects",
    description: "Web3 ETH & SOL Wallet with decentralized asset tracking.",
    githubUrl: "https://github.com/iamkaifyyy/Odyssey.git",
    liveUrl: "https://odyssey-1yjh.vercel.app",
    videoUrl: "/recordings/odyssey.mp4",
    tag: "Solana & EVM",
    tech: ["Solana", "Ethereum", "React", "Ethers.js"],
  },
  {
    id: "project-ui",
    name: "Unreal UI",
    category: "projects",
    description: "Fast, Flexible, and Fully Customizable UI Components.",
    githubUrl: "https://github.com/iamkaifyyy/Unreal-UI-",
    liveUrl: "https://onewavestudio.vercel.app/",
    videoUrl: "/recordings/ui.mp4",
    tag: "Building",
    tech: ["React.js", "Tailwind CSS", "TypeScript"],
  },
];

export const DESIGNS_DATA: Project[] = [
  {
    id: "design-zone",
    name: "Zone",
    category: "design",
    description: "Secure your code ownership on the Solana blockchain. Protect IP and build a verifiable portfolio.",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://onewavestudio.vercel.app/",
    videoUrl: "/recordings/Zone.mp4",
    tag: "Motion",
    tech: ["Figma", "Solana", "Motion"],
  },
  {
    id: "design-perplexity",
    name: "Perplexity",
    category: "design",
    description: "Better design and landing page for perplexity made with figma",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://onewavestudio.vercel.app/",
    videoUrl: "/recordings/Perplexity.mp4",
    tag: "Figma",
    tech: ["Figma", "UI/UX", "Landing Page"],
  },
  {
    id: "design-zerotwo",
    name: "Zero Two",
    category: "design",
    description: "Elevate your space with premium collection of anime-inspired stickers, posters, and bookmarks",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://onewavestudio.vercel.app/",
    videoUrl: "/recordings/Zerotwo.mp4",
    tag: "Motion",
    tech: ["Framer", "Motion Design"],
  },
  {
    id: "design-click",
    name: "Click",
    category: "design",
    description: "Revamped the UI with minimalist design of Pika.style along with UX",
    githubUrl: "https://github.com/iamkaifyyy",
    liveUrl: "https://onewavestudio.vercel.app/",
    videoUrl: "/recordings/click.mp4",
    tag: "Framer",
    tech: ["Framer", "Minimalist UX"],
  },
];
